-- Seed missions for the JOMO Guide board. Re-runnable: clears prior seed rows first.
-- Source of truth: seed/missions.json
update public.profiles set display_name = 'JOMO Guide' where id = '254232f7-3ee3-4d1d-8342-e09b41f7a166';
delete from public.missions where creator_id = '254232f7-3ee3-4d1d-8342-e09b41f7a166';
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Teach someone your favourite knot','Anywhere, anytime. Takes four minutes. They will use it all week.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Bring water to someone building in the sun','Look for the people still hauling at 2pm. They have forgotten to drink.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Sit with a stranger for ten minutes and say nothing','Agree to it out loud first. Then just sit. It is harder and better than it sounds.','limited',8);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Find whoever made your favourite thing here and tell them','Someone spent months on the thing you walked past. Go back. Say so.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Carry something heavy for a camp that isn''t yours','No need to ask what it''s for. Just take one end.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Leave a written note where it will be found tomorrow','Not signed. Not clever. Just kind.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Cook for someone who forgot to eat','There is always at least one. Usually they are the one cooking for everyone else.','limited',10);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Learn one song well enough to sing it at 3am','You will need it. Someone will need it.','limited',5);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','MOOP sweep a plaza at sunrise','One person, one plaza, one hour, before anyone is awake to see you do it.','exclusive',1);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Give away the thing you''re most attached to','Not the spare one. The one you''d rather keep.','exclusive',1);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Ask three people what they''re afraid of','Answer first, honestly, or it doesn''t count.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Repair something broken that isn''t yours','Gaffer tape counts. Doing it without being asked is the point.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Walk someone home who is lost','All the way. Not just pointing.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Hold space at Sanctuary for an hour','Only if you are steady today. Check in with the crew there first.','limited',4);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Photograph nothing for a whole day','Describe one thing out loud to someone instead. See which one you remember in a year.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Make a stranger laugh before breakfast','Low bar. Early hours. Surprisingly difficult.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Take a shift nobody signed up for','Check the boards for the gaps. The 4am ones. Those.','limited',6);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Introduce two people who should know each other','Say why, out loud, to both of them. Then leave.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Thank whoever is still playing at 5am','When the floor is nearly empty is exactly when it matters.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Wash dishes for a camp that fed you','Don''t ask. Just start.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Get up for sunrise once','Once. That''s the whole mission.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Ask someone to teach you the thing they''re best at','Everyone here is unreasonably good at something. Find out what.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Sit somewhere dark and listen for ten minutes','No phone. Away from the sound systems. You will hear the whole place breathing.','open',null);
insert into public.missions (creator_id,title,description,capacity_type,capacity) values ('254232f7-3ee3-4d1d-8342-e09b41f7a166','Write down one thing you''re taking home','Then give the note to whoever caused it.','open',null);
